module.exports = {
    _skuPath: '"//sku.test.duia.com"',
    _mlistPath: '"//mlist1.test.duia.com"',
    _listPath: '"//list1.test.duia.com"',
    _tuPath: '"//tu.test.duia.com/"',
    _ucPath: '"//uc.test.duia.com"',
    _mucPath: '"//muc.test.duia.com"',
    _ssoPath: '"//sso.test.duia.com"',
    _livePath: '"//live.test.duia.com"',
    _itemPath: '"//item.test.duia.com"',
    _mitemPath: '"//mitem.test.duia.com"',
    _zhaopinPath: '"//zhaopin.test.duia.com"',
    _wechatPath: '"//wechat.api.test.duia.com"',
    _bangPath: '"//bang.test.duia.com"',
    _commonStaticPath: '"//common.test.duia.com"',
    _ntikuPath: '"//ntiku.test.duia.com"',
    _aiPath: '"//ai.api.test.duia.com"',
    _ucapiPath: '"//ucapi.test.duia.com"',
    _commodityPath: '"//commodity.test.duia.com"',
    _ntkPath: '"//ntk.test.duia.com"',
    _loginPath: '"//login.test.duia.com"',
    _resourceapiPath: '"//resourceapi.test.duia.com"'
};
